#!/bin/bash

install_dependencies() {
    sudo apt-get update
    sudo apt-get install -y nginx docker.io net-tools
}

configure_service() {
    # Create log file and set permissions
    sudo touch /var/log/devopsfetch.log
    sudo chmod 664 /var/log/devopsfetch.log
    sudo chown root:syslog /var/log/devopsfetch.log
    
    sudo bash -c 'cat > /etc/systemd/system/sysinfo.service << EOF
[Unit]
Description=System Information Service

[Service]
ExecStart=/home/dmex/hng-task5/monitoring-script/devopsfetch -d
StandardOutput=append:/var/log/devopsfetch.log
StandardError=append:/var/log/devopsfetch.log
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF'
    sudo systemctl daemon-reload
    sudo systemctl enable sysinfo.service
    sudo systemctl start sysinfo.service
}

configure_log_rotation() {
    sudo bash -c 'cat > /etc/logrotate.d/sysinfo << EOF
/var/log/devopsfetch.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 root utmp
    sharedscripts
    postrotate
        systemctl restart sysinfo.service > /dev/null
    endscript
}
EOF'
}

execute_all() {
    install_dependencies
    configure_service
    configure_log_rotation
}

execute_all